version: '3.8'

services:
  postgres:
    image: postgres
    container_name: gestao_vagas_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gestao_vagas
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data