version: '3.8'

networks:
  gestao_vagas_net:
    driver: bridge

volumes:
  prometheus_data:
  grafana_data:

services:
  postgres:
    image: postgres
    container_name: gestao_vagas_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gestao_vagas
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data

  prometheus:
    image: prom/prometheus
    container_name: gestao_vagas_prometheus
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - gestao_vagas_net

  grafana:
    image: grafana/grafana
    container_name: gestao_vagas_grafana
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - "3000:3000"
    networks:
      - gestao_vagas_net